version: '3.8'


services:
  mysqldb:
    container_name: microservices-mysqldb
    image: mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
    ports:
      - $DOCKER_DB_PORT:$DB_PORT
  app:
    container_name: microservices-node-back
    restart: unless-stopped
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - 3000:3000
    volumes:
      - .:/app
  adminer:
    image: adminer
    ports:
      - 8080:8080